Trivial project file tidy-up
* Moved the documentation build script to a new location (utils directory) and improved
  it so that it gives feedback if the page builder is not found.

* Created a new helper script to clean the project up.

* Removed some obsolete documentation.

diff --git a/utils/build-documentation b/utils/build-documentation
--- a/utils/build-documentation
+++ b/utils/build-documentation
@@ -16,5 +16,12 @@ else
   output_option=""
 fi
 
+if [ ! -e "${builder_app}" ]
+then
+  echo "Cannot find the page builder application at '${builder_app}'"
+  echo "Has the solution been compiled?"
+  exit 1
+fi
+
 $builder_app -e html -c "baseUrl=http://csf-software-development.github.com/ZPT-Sharp/;timestamp=${current_timestamp}" $output_option "$input_path"
 cp -r "${input_path}/static" "${output_path}"
